// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface DAO { created_at: string, setup_at: string, factory_account_id: string, }