// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface Metadata { id: string, expires_at: string, funding_amount_limit: string, unpaid_amount: string, nep_141: string, maintainer_account_id: string, metadata_url: string, }